services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-earthflow}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  backend:
    image: ghcr.io/saliou33/earthflow-backend:latest
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-earthflow}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - TITILER_ENDPOINT=${TITILER_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-admin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-password}
      - RUST_ENV=production
    depends_on:
      - db

  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    ports:
      - "8001:80"
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER:-admin}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-password}
      - AWS_REGION=us-east-1
      - AWS_S3_ENDPOINT=${MINIO_ENDPOINT}
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_VIRTUAL_HOSTING=FALSE
      - AWS_HTTPS=NO

volumes:
  db_data:

networks:
  earthflow-network:
    external: true
